apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: cgraham-dev-tls
spec:
  secretName: cgraham-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cgraham.dev
  dnsNames:
    - cgraham.dev
    - www.cgraham.dev